print("Una computadora puede ser llamada \"inteligente\" si logra engañar a una persona haciéndole creer que es un humano")
print('Una computadora puede ser llamada "inteligente" si logra engañar a una persona haciéndole creer que es un humano')
print("Una computadora puede ser llamada 'inteligente' si logra engañar a una persona haciéndole creer que es un humano")
print(6+3)
print(6-6)
print(6*3)
print(6/3)
print(6//3)
print(6**3)
print(6%3)
print(type("hola"))